wandb_version: 1

ARCHIVE_CHECKPOINT_GAP:
  desc: null
  value: 2000
ARCHIVE_CHECKPOINT_START_EPISODE:
  desc: null
  value: 8000
BATCH_SIZE:
  desc: null
  value: 128
DECAY_STEP:
  desc: null
  value: 256
EMBEDDING_DIM:
  desc: null
  value: 128
FOLDER_NAME:
  desc: null
  value: ae_clean
GAMMA:
  desc: null
  value: 1
INPUT_DIM:
  desc: null
  value: 7
K_SIZE:
  desc: null
  value: 20
LOAD_MODEL:
  desc: null
  value: false
LR:
  desc: null
  value: 1.0e-05
MINIMUM_BUFFER_SIZE:
  desc: null
  value: 2000
NODE_PADDING_SIZE:
  desc: null
  value: 360
NUM_GPU:
  desc: null
  value: 1
NUM_META_AGENT:
  desc: null
  value: 32
REPLAY_SIZE:
  desc: null
  value: 10000
SAVE_IMG_GAP:
  desc: null
  value: 100
SUMMARY_WINDOW:
  desc: null
  value: 32
USE_GPU:
  desc: null
  value: false
USE_GPU_GLOBAL:
  desc: null
  value: true
USE_WANDB:
  desc: null
  value: true
WANDB_ENTITY:
  desc: null
  value: null
WANDB_MODE:
  desc: null
  value: online
WANDB_PROJECT:
  desc: null
  value: ARiADNE
_wandb:
  desc: null
  value:
    cli_version: 0.13.11
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.8
    start_time: 1779261082.589788
    t:
      1:
      - 1
      - 5
      - 30
      - 53
      - 55
      2:
      - 1
      - 5
      - 30
      - 53
      - 55
      3:
      - 2
      - 13
      - 16
      - 23
      4: 3.10.8
      5: 0.13.11
      8:
      - 5
gifs_path:
  desc: null
  value: gifs/ae_clean
model_path:
  desc: null
  value: model/ae_clean
train_path:
  desc: null
  value: train/ae_clean
